baseURL = 'http://perfectkars.github.io/'
languageCode = 'zh-CN'
defaultContentLanguage= 'zh'
title = 'PerfectKars'
theme = 'fluency'
enableRobotsTXT=true

# Code Highlight
pygmentsUseClasses = true # enable theme-defined highlight style
pygmentsCodefences = true

enableEmoji=true

disqusShortname = "perfectkars"

[params]
	copyright = "© Perfectkars"

[params.pageSize]
index= 5
list= 10
terms= 60
archives= 20

# Social Tags

[[menu.footer]]
name = "GitHub"
identifier = "github"
url = "https://github.com/perfectkars"

[[menu.footer]]
name = "Twitter"
identifier = "twitter"
url = "https://twitter.com/xiaomayiyahei"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Moment"
url = "/moment"
weight = 5